### ISSUE TITLE
Проблема архитектуры ActiveField

### ISSUE THREAD

**Issue by pavel-koryagin** [jiisoft/jii-view#1]
Она сейчас хранит errors у себя. Таким образом она не может отозваться на errors, пришедшие с сервера. 

Считаю, что ReactWay - это 
а) все данные, включая сообщения об ошибках, получать из модели - для React они все равны и 
б) всё-таки не использовать defaultValue, а потому что они рекомендуют использовать value http://center.koryagin.com/i/2016-06-13_21%3A13%3A14_c7c931cf0878f8f74dc8.png

В этом случае модель будет получать новое value на каждый символ. Сейчас модель получает value + обнуление ошибок по этому атрибуту в произвольный момент времени. Так что на каждый символ, хоть и вызывает задумчивость, всё ж последовательнее, чем сейчас.

Да, на вопрос, что ж делать с избытком событий change в модели, тоже придётся найти ответ.

**Comment by affka** [comment]
добавлено событие change_errors, убран defaultValue
